name: downloadsymbols

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Install BCContainerHelper
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module BCContainerHelper
      
      - name: Get artifact url
        shell: pwsh
        run: |
          $ArtifactUrl = Get-BCArtifactUrl -type Sandbox -select Latest -Country nl;
          echo "##vso[task.setvariable variable=ARTIFACTURL]$ArtifactUrl"
          $GetArtifacts = Download-Artifacts $ArtifactUrl
          # Applications.NL\Microsoft_Base Application_22.5.59966.60256.app
          $SearchString  = "Applications.*\Microsoft_Base Application*.app"
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            c:\bcartifacts.cache\sandbox\*\*\Applications.*\Microsoft_Base Application*.app
            c:\bcartifacts.cache\sandbox\*\*\Applications.*\Microsoft_Application*.app