name: downloadsymbols

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Module
        id: myCache
        uses: actions/cache@v2
        with:
          path: c:\users\runneradmin\documents\windowspowershell\modules\bccontainerhelper
          key: ${{ runner.os }}-bccontainerhelper-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-bccontainerhelper-

      - name: Install BCContainerHelper
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module BCContainerHelper

      - name: Get artifact url
        shell: pwsh
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull

          'be', 'de', 'nl' | ForEach-Object {
            $ArtifactUrl = Get-BCArtifactUrl -type Sandbox -select Latest -Country $_
            Download-Artifacts $ArtifactUrl -includePlatform | Out-Null

            Copy-Item -Path 'c:\bcartifacts.cache\sandbox\*\*\Applications.*\Microsoft_Base Application*.app' -Destination "./$($_)"  -Force
            Copy-Item -Path 'c:\bcartifacts.cache\sandbox\*\*\Applications.*\Microsoft_Application*.app' -Destination "./$($_)" -Recurse -Force
            Copy-Item -Path 'c:\bcartifacts.cache\sandbox\*\*\Applications.*\Microsoft_System*.app' -Destination "./$($_)" -Recurse -Force
            Copy-Item -Path 'c:\bcartifacts.cache\sandbox\*\platform\ModernDev\program files\Microsoft Dynamics NAV\*\AL Development Environment\System.app' -Destination "./$($_)" -Recurse -Force
          }

          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push