name: downloadsymbols

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONTAINERNAME: roy
  USERNAME: admin
  PASSWORD: admin

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Install BCContainerHelper
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module BCContainerHelper

      - name: Create container
        shell: pwsh
        run: |
          $ArtifactUrl = Get-BCArtifactUrl -type Sandbox -select Latest -Country nl;
          $Credential = [PSCredential]::new('$USERNAME', (ConvertTo-SecureString '$PASSWORD' -AsPlainText -Force));
          New-BcContainer -accept_eula -accept_outdated -containerName '$CONTAINERNAME' -auth NavUserPassword -credential $Credential -artifactUrl $artifactUrl -shortcuts None -useBestContainerOS -updateHosts;

      - name: Download symbols
        shell: pwsh
        run: |
          $Credential = [PSCredential]::new('$USERNAME', (ConvertTo-SecureString '$PASSWORD' -AsPlainText -Force));
          Get-BCContainerApp -containerName '$CONTAINERNAME' -appName 'Base Application' -credential $Credential -appFile './BaseApplication.App'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Symbols
          path: |
            ./BaseApplication.app